package com.example.lenovo.xiongmaopindao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lenovo.xiongmaopindao.sqilts.AlllistBean;
import com.example.lenovo.xiongmaopindao.sqilts.TablistBean;

import com.example.lenovo.xiongmaopindao.AlllistBeanDao;
import com.example.lenovo.xiongmaopindao.TablistBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alllistBeanDaoConfig;
    private final DaoConfig tablistBeanDaoConfig;

    private final AlllistBeanDao alllistBeanDao;
    private final TablistBeanDao tablistBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alllistBeanDaoConfig = daoConfigMap.get(AlllistBeanDao.class).clone();
        alllistBeanDaoConfig.initIdentityScope(type);

        tablistBeanDaoConfig = daoConfigMap.get(TablistBeanDao.class).clone();
        tablistBeanDaoConfig.initIdentityScope(type);

        alllistBeanDao = new AlllistBeanDao(alllistBeanDaoConfig, this);
        tablistBeanDao = new TablistBeanDao(tablistBeanDaoConfig, this);

        registerDao(AlllistBean.class, alllistBeanDao);
        registerDao(TablistBean.class, tablistBeanDao);
    }
    
    public void clear() {
        alllistBeanDaoConfig.clearIdentityScope();
        tablistBeanDaoConfig.clearIdentityScope();
    }

    public AlllistBeanDao getAlllistBeanDao() {
        return alllistBeanDao;
    }

    public TablistBeanDao getTablistBeanDao() {
        return tablistBeanDao;
    }

}
